import Head from "next/head";
// import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useUser } from "@auth0/nextjs-auth0";
import { useEnsureUser } from "@/hooks/useEnsureUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  const { user, isLoading } = useUser();
  useEnsureUser();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Your Next Marketing Team</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        Home Page
        {user ? (
          <div className={styles.user}>
            <p>Welcome, {user.name}!</p>
            <Link href="/">Go to Dashboarddd</Link>
            <br />
            <Link href="/auth/logout">Log Out</Link>
          </div>
        ) : (
          <div className={styles.user}>
            <p>Please log in to access your dashboard.</p>
            <Link href="/auth/login">Log In</Link>
          </div>
        )}
      </div>
    </>
  );
}
